/** AUTOGENERATED CODE BELOW **/

function notImplemented() {
  console.log("Not yet implemented");
}


// Type: Core

/**
 * @param value
 * @return any
 */
export function disambiguated_ltrim(value: any): any {
  notImplemented();
  return null;
}
// end Type
