/** AUTOGENERATED CODE BELOW **/

function notImplemented() {
  console.log("Not yet implemented");
}


export class Directory {
  
  /**
   * 
   */
  private static m_applicationDataPath: any;
  static get applicationDataPath(): any {
    return this.m_applicationDataPath;
  }
  static set applicationDataPath(value: any) {
    this.m_applicationDataPath = value;
  }
}
