/* AUTOGENERATED CODE BELOW */

function notImplemented() {
  console.log("Not yet implemented");
}


export class Directory {
  
  /**
   * 
   */
  private msource: any;
  get source(): any {
    return this.msource;
  }
  set source(value: any) {
    this.msource = value;
  }
}
