/** AUTOGENERATED CODE BELOW **/

function notImplemented() {
  console.log("Not yet implemented");
}


export class Directory {
  
  /**
   * 
   */
  private m_applicationDataPath: any;
  get applicationDataPath(): any {
    return this.m_applicationDataPath;
  }
  
  
  /**
   * 
   */
  private static m_externalFilesPath: any;
  static get externalFilesPath(): any {
    return this.m_externalFilesPath;
  }
  
}
