/* AUTOGENERATED CODE BELOW */

function notImplemented() {
  console.log("Not yet implemented");
}


export class Directory {
  
  /**
   * 
   */
  private static mapplicationDataPath: any;
  static get applicationDataPath(): any {
    return this.mapplicationDataPath;
  }
  static set applicationDataPath(value: any) {
    this.mapplicationDataPath = value;
  }
}
