/** AUTOGENERATED CODE BELOW **/

function notImplemented() {
  console.log("Not yet implemented");
}


export class Core {
  
  /**
   * @param Value
   * @param Months
   */
  static AddMth(self: any, Value: Date, Months: number) {
    notImplemented();
  }
}
