/** AUTOGENERATED CODE BELOW **/

function notImplemented() {
  console.log("Not yet implemented");
}


export class Numeric {
  
  /**
   * @return any
   */
  static IsEmpty(self: any): any {
    notImplemented();
    return null;
  }
}
