/* AUTOGENERATED CODE BELOW */

function notImplemented() {
  console.log("Not yet implemented");
}


export class Numeric {
  
  /**
   * @return any
   */
  isEmpty(): any {
    notImplemented();
    return null;
  }
}
