/** AUTOGENERATED CODE BELOW **/

function notImplemented() {
  console.log("Not yet implemented");
}


export class Directory {
  
  /**
   * 
   */
  private m_source: any;
  get source(): any {
    return this.m_source;
  }
  set source(value: any) {
    this.m_source = value;
  }
}
