/** AUTOGENERATED CODE BELOW **/

function notImplemented() {
  console.log("Not yet implemented");
}


export class Date {
  
  /**
   * @param Year
   * @param Month
   * @param Day
   * @return Date
   */
  static New(Year: number, Month: number, Day: number): Date {
    notImplemented();
    return null;
  }
}
