/** AUTOGENERATED CODE BELOW **/

function notImplemented() {
  console.log("Not yet implemented");
}


export class Date {
  
  /**
   * @return any
   */
  toString(): any {
    notImplemented();
    return null;
  }
  
  /**
   * @param year
   * @param month
   * @param day
   * @return Date
   */
  static new(year: number, month: number, day: number): Date {
    notImplemented();
    return null;
  }
}
