/* AUTOGENERATED CODE BELOW */

function notImplemented(fnName: string) {
  console.log(`Not yet implemented: ${fnName}`);
}


// Type: Core

/**
 * @param value
 * @return any
 */
export function disambiguatedltrim(...args: any[]): any {
  notImplemented("disambiguatedltrim");
  return null;
}
// end Type
