/* AUTOGENERATED CODE BELOW */

function notImplemented() {
  console.log("Not yet implemented");
}


// Type: Boolean

/**
 * @return boolean
 */
export function method(): boolean {
  notImplemented();
  return null;
}
// end Type
