/* AUTOGENERATED CODE BELOW */

function notImplemented(fnName: string) {
  console.log(`Not yet implemented: ${fnName}`);
}


// Type: Boolean

/**
 * @return boolean
 */
export function method(...args: any[]): any {
  notImplemented("method");
  return null;
}
// end Type
