/* AUTOGENERATED CODE BELOW */

function notImplemented(fnName: string) {
  console.log(`Not yet implemented: ${fnName}`);
}


// Type: Numeric

/**
 * @return number
 */
export function integer(...args: any[]): any {
  notImplemented("integer");
  return null;
}

/**
 * @param value
 * @return any
 */
export function fromString(...args: any[]): any {
  notImplemented("fromString");
  return null;
}

/**
 * @param pDecimals
 * @return number
 */
export function round(...args: any[]): any {
  notImplemented("round");
  return null;
}

/**
 * @param pDecimals
 * @return number
 */
export function roundToEven(...args: any[]): any {
  notImplemented("roundToEven");
  return null;
}

/**
 * @return any
 */
export function toString(...args: any[]): any {
  notImplemented("toString");
  return null;
}

/**
 * @param pDecimals
 * @return number
 */
export function truncate(...args: any[]): any {
  notImplemented("truncate");
  return null;
}
// end Type
