/* AUTOGENERATED CODE BELOW */

function notImplemented() {
  console.log("Not yet implemented");
}


// Type: Numeric

/**
 * @return number
 */
export function integer(): number {
  notImplemented();
  return null;
}

/**
 * @param value
 * @return any
 */
export function fromString(value: any): any {
  notImplemented();
  return null;
}

/**
 * @param pDecimals
 * @return number
 */
export function round(pDecimals: number): number {
  notImplemented();
  return null;
}

/**
 * @param pDecimals
 * @return number
 */
export function roundToEven(pDecimals: number): number {
  notImplemented();
  return null;
}

/**
 * @return any
 */
export function toString(): any {
  notImplemented();
  return null;
}

/**
 * @param pDecimals
 * @return number
 */
export function truncate(pDecimals: number): number {
  notImplemented();
  return null;
}
// end Type
