/* AUTOGENERATED CODE BELOW */

function notImplemented(fnName: string) {
  console.log(`Not yet implemented: ${fnName}`);
}


export class Numeric {
  
  /**
   * @return boolean
   */
  isEmpty(...args: any[]): any {
    notImplemented("isEmpty");
    return null;
  }
}
