/* AUTOGENERATED CODE BELOW */

function notImplemented(fnName: string) {
  console.log(`Not yet implemented: ${fnName}`);
}


export class Date {
  
  /**
   * @return any
   */
  toString(...args: any[]): any {
    notImplemented("toString");
    return null;
  }
  
  /**
   * @param year
   * @param month
   * @param day
   * @return Date
   */
  static new(...args: any[]): any {
    notImplemented("new");
    return null;
  }
}
