/* AUTOGENERATED CODE BELOW */

function notImplemented() {
  console.log("Not yet implemented");
}


// Type: Core

/**
 * @param value
 * @param months
 * @return Date
 */
export function addMth(value: Date, months: number): Date {
  notImplemented();
  return null;
}
// end Type
