/* AUTOGENERATED CODE BELOW */

function notImplemented(fnName: string) {
  console.log(`Not yet implemented: ${fnName}`);
}


export class Directory {
  
  /**
   * 
   */
  private mapplicationDataPath: any;
  get applicationDataPath(): any {
    return this.mapplicationDataPath;
  }
  
  
  /**
   * 
   */
  private static mexternalFilesPath: any;
  static get externalFilesPath(): any {
    return this.mexternalFilesPath;
  }
  
}
