/* AUTOGENERATED CODE BELOW */

function notImplemented(fnName: string) {
  console.log(`Not yet implemented: ${fnName}`);
}


// Type: Core

/**
 * @param value
 * @param months
 * @return Date
 */
export function addMth(...args: any[]): any {
  notImplemented("addMth");
  return null;
}
// end Type
