/* AUTOGENERATED CODE BELOW */

function notImplemented(fnName: string) {
  console.log(`Not yet implemented: ${fnName}`);
}


export class Directory {
  
  /**
   * 
   */
  private msource: any;
  get source(): any {
    return this.msource;
  }
  set source(value: any) {
    this.msource = value;
  }
}
